// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: capy/capy/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dc0989f74d7e251, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dc0989f74d7e251, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetAnimalsRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetAnimalsRequest) Reset()         { *m = QueryGetAnimalsRequest{} }
func (m *QueryGetAnimalsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetAnimalsRequest) ProtoMessage()    {}
func (*QueryGetAnimalsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dc0989f74d7e251, []int{2}
}
func (m *QueryGetAnimalsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAnimalsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAnimalsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAnimalsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAnimalsRequest.Merge(m, src)
}
func (m *QueryGetAnimalsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAnimalsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAnimalsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAnimalsRequest proto.InternalMessageInfo

func (m *QueryGetAnimalsRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetAnimalsResponse struct {
	Animals Animals `protobuf:"bytes,1,opt,name=Animals,proto3" json:"Animals"`
}

func (m *QueryGetAnimalsResponse) Reset()         { *m = QueryGetAnimalsResponse{} }
func (m *QueryGetAnimalsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetAnimalsResponse) ProtoMessage()    {}
func (*QueryGetAnimalsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dc0989f74d7e251, []int{3}
}
func (m *QueryGetAnimalsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAnimalsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAnimalsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAnimalsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAnimalsResponse.Merge(m, src)
}
func (m *QueryGetAnimalsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAnimalsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAnimalsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAnimalsResponse proto.InternalMessageInfo

func (m *QueryGetAnimalsResponse) GetAnimals() Animals {
	if m != nil {
		return m.Animals
	}
	return Animals{}
}

type QueryAllAnimalsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllAnimalsRequest) Reset()         { *m = QueryAllAnimalsRequest{} }
func (m *QueryAllAnimalsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllAnimalsRequest) ProtoMessage()    {}
func (*QueryAllAnimalsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dc0989f74d7e251, []int{4}
}
func (m *QueryAllAnimalsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllAnimalsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllAnimalsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllAnimalsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllAnimalsRequest.Merge(m, src)
}
func (m *QueryAllAnimalsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllAnimalsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllAnimalsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllAnimalsRequest proto.InternalMessageInfo

func (m *QueryAllAnimalsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllAnimalsResponse struct {
	Animals    []Animals           `protobuf:"bytes,1,rep,name=Animals,proto3" json:"Animals"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllAnimalsResponse) Reset()         { *m = QueryAllAnimalsResponse{} }
func (m *QueryAllAnimalsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllAnimalsResponse) ProtoMessage()    {}
func (*QueryAllAnimalsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dc0989f74d7e251, []int{5}
}
func (m *QueryAllAnimalsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllAnimalsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllAnimalsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllAnimalsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllAnimalsResponse.Merge(m, src)
}
func (m *QueryAllAnimalsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllAnimalsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllAnimalsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllAnimalsResponse proto.InternalMessageInfo

func (m *QueryAllAnimalsResponse) GetAnimals() []Animals {
	if m != nil {
		return m.Animals
	}
	return nil
}

func (m *QueryAllAnimalsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetAnimalSkillRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetAnimalSkillRequest) Reset()         { *m = QueryGetAnimalSkillRequest{} }
func (m *QueryGetAnimalSkillRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetAnimalSkillRequest) ProtoMessage()    {}
func (*QueryGetAnimalSkillRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dc0989f74d7e251, []int{6}
}
func (m *QueryGetAnimalSkillRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAnimalSkillRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAnimalSkillRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAnimalSkillRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAnimalSkillRequest.Merge(m, src)
}
func (m *QueryGetAnimalSkillRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAnimalSkillRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAnimalSkillRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAnimalSkillRequest proto.InternalMessageInfo

func (m *QueryGetAnimalSkillRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetAnimalSkillResponse struct {
	AnimalSkill AnimalSkill `protobuf:"bytes,1,opt,name=AnimalSkill,proto3" json:"AnimalSkill"`
}

func (m *QueryGetAnimalSkillResponse) Reset()         { *m = QueryGetAnimalSkillResponse{} }
func (m *QueryGetAnimalSkillResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetAnimalSkillResponse) ProtoMessage()    {}
func (*QueryGetAnimalSkillResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dc0989f74d7e251, []int{7}
}
func (m *QueryGetAnimalSkillResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAnimalSkillResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAnimalSkillResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAnimalSkillResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAnimalSkillResponse.Merge(m, src)
}
func (m *QueryGetAnimalSkillResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAnimalSkillResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAnimalSkillResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAnimalSkillResponse proto.InternalMessageInfo

func (m *QueryGetAnimalSkillResponse) GetAnimalSkill() AnimalSkill {
	if m != nil {
		return m.AnimalSkill
	}
	return AnimalSkill{}
}

type QueryAllAnimalSkillRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllAnimalSkillRequest) Reset()         { *m = QueryAllAnimalSkillRequest{} }
func (m *QueryAllAnimalSkillRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllAnimalSkillRequest) ProtoMessage()    {}
func (*QueryAllAnimalSkillRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dc0989f74d7e251, []int{8}
}
func (m *QueryAllAnimalSkillRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllAnimalSkillRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllAnimalSkillRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllAnimalSkillRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllAnimalSkillRequest.Merge(m, src)
}
func (m *QueryAllAnimalSkillRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllAnimalSkillRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllAnimalSkillRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllAnimalSkillRequest proto.InternalMessageInfo

func (m *QueryAllAnimalSkillRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllAnimalSkillResponse struct {
	AnimalSkill []AnimalSkill       `protobuf:"bytes,1,rep,name=AnimalSkill,proto3" json:"AnimalSkill"`
	Pagination  *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllAnimalSkillResponse) Reset()         { *m = QueryAllAnimalSkillResponse{} }
func (m *QueryAllAnimalSkillResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllAnimalSkillResponse) ProtoMessage()    {}
func (*QueryAllAnimalSkillResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dc0989f74d7e251, []int{9}
}
func (m *QueryAllAnimalSkillResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllAnimalSkillResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllAnimalSkillResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllAnimalSkillResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllAnimalSkillResponse.Merge(m, src)
}
func (m *QueryAllAnimalSkillResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllAnimalSkillResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllAnimalSkillResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllAnimalSkillResponse proto.InternalMessageInfo

func (m *QueryAllAnimalSkillResponse) GetAnimalSkill() []AnimalSkill {
	if m != nil {
		return m.AnimalSkill
	}
	return nil
}

func (m *QueryAllAnimalSkillResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "capy.capy.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "capy.capy.QueryParamsResponse")
	proto.RegisterType((*QueryGetAnimalsRequest)(nil), "capy.capy.QueryGetAnimalsRequest")
	proto.RegisterType((*QueryGetAnimalsResponse)(nil), "capy.capy.QueryGetAnimalsResponse")
	proto.RegisterType((*QueryAllAnimalsRequest)(nil), "capy.capy.QueryAllAnimalsRequest")
	proto.RegisterType((*QueryAllAnimalsResponse)(nil), "capy.capy.QueryAllAnimalsResponse")
	proto.RegisterType((*QueryGetAnimalSkillRequest)(nil), "capy.capy.QueryGetAnimalSkillRequest")
	proto.RegisterType((*QueryGetAnimalSkillResponse)(nil), "capy.capy.QueryGetAnimalSkillResponse")
	proto.RegisterType((*QueryAllAnimalSkillRequest)(nil), "capy.capy.QueryAllAnimalSkillRequest")
	proto.RegisterType((*QueryAllAnimalSkillResponse)(nil), "capy.capy.QueryAllAnimalSkillResponse")
}

func init() { proto.RegisterFile("capy/capy/query.proto", fileDescriptor_2dc0989f74d7e251) }

var fileDescriptor_2dc0989f74d7e251 = []byte{
	// 577 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x51, 0x6b, 0x13, 0x41,
	0x10, 0xce, 0xa5, 0x31, 0xe2, 0x16, 0x0a, 0xd9, 0xc6, 0xc4, 0x9e, 0xf1, 0xaa, 0x8b, 0xd6, 0xa2,
	0x72, 0x4b, 0xe3, 0xbb, 0x90, 0x3e, 0xb4, 0x4f, 0x42, 0x8d, 0x6f, 0x82, 0xe8, 0xa6, 0x59, 0x8e,
	0xc3, 0xcb, 0xed, 0x25, 0x7b, 0x15, 0x83, 0x08, 0xd2, 0x5f, 0x20, 0x08, 0xfe, 0x04, 0x7f, 0x4b,
	0x1f, 0x0b, 0x3e, 0xe8, 0x93, 0x48, 0xe2, 0x0f, 0x91, 0xdb, 0x9d, 0x24, 0x77, 0xb7, 0x97, 0xd6,
	0x42, 0x5e, 0x8e, 0x63, 0xe6, 0x9b, 0xf9, 0xbe, 0x99, 0xd9, 0x19, 0x74, 0xf3, 0x98, 0x45, 0x63,
	0xaa, 0x3e, 0xc3, 0x13, 0x3e, 0x1a, 0xbb, 0xd1, 0x48, 0xc4, 0x02, 0xdf, 0x48, 0x2c, 0x6e, 0xf2,
	0xb1, 0xeb, 0x9e, 0xf0, 0x84, 0xb2, 0xd2, 0xe4, 0x4f, 0x03, 0xec, 0x96, 0x27, 0x84, 0x17, 0x70,
	0xca, 0x22, 0x9f, 0xb2, 0x30, 0x14, 0x31, 0x8b, 0x7d, 0x11, 0x4a, 0xf0, 0x3e, 0x3a, 0x16, 0x72,
	0x20, 0x24, 0xed, 0x31, 0xc9, 0x75, 0x5e, 0xfa, 0x7e, 0xaf, 0xc7, 0x63, 0xb6, 0x47, 0x23, 0xe6,
	0xf9, 0xa1, 0x02, 0x03, 0xb6, 0xb1, 0x50, 0x10, 0xb1, 0x11, 0x1b, 0xcc, 0x72, 0x34, 0x17, 0x76,
	0x16, 0xfa, 0x03, 0x16, 0xcc, 0x1c, 0xad, 0xbc, 0xe3, 0x8d, 0x7c, 0xe7, 0x07, 0x81, 0xf6, 0x92,
	0x3a, 0xc2, 0x2f, 0x12, 0xc2, 0x23, 0x95, 0xab, 0xcb, 0x87, 0x27, 0x5c, 0xc6, 0xe4, 0x00, 0x6d,
	0x66, 0xac, 0x32, 0x12, 0xa1, 0xe4, 0x98, 0xa2, 0xaa, 0xe6, 0xbc, 0x65, 0xdd, 0xb5, 0x76, 0xd7,
	0xdb, 0x35, 0x77, 0x5e, 0xb7, 0xab, 0xa1, 0xfb, 0x95, 0xb3, 0xdf, 0xdb, 0xa5, 0x2e, 0xc0, 0xc8,
	0x2e, 0x6a, 0xa8, 0x3c, 0x87, 0x3c, 0xee, 0x68, 0x51, 0xc0, 0x80, 0x37, 0x50, 0xd9, 0xef, 0xab,
	0x34, 0x95, 0x6e, 0xd9, 0xef, 0x93, 0xe7, 0xa8, 0x69, 0x20, 0x81, 0xb5, 0x8d, 0xae, 0x83, 0x09,
	0x68, 0x71, 0x8a, 0x16, 0x3c, 0xc0, 0x3b, 0x03, 0x92, 0xb7, 0x40, 0xdc, 0x09, 0x82, 0x1c, 0xf1,
	0x01, 0x42, 0x8b, 0x9e, 0x42, 0xc2, 0x1d, 0x57, 0x0f, 0xc0, 0x4d, 0x06, 0xe0, 0xea, 0xc1, 0xc2,
	0x00, 0xdc, 0x23, 0xe6, 0x71, 0x88, 0xed, 0xa6, 0x22, 0xc9, 0x37, 0x0b, 0x14, 0xa7, 0x29, 0x8a,
	0x14, 0xaf, 0xfd, 0x97, 0x62, 0x7c, 0x98, 0xd1, 0x55, 0x56, 0xba, 0x1e, 0x5e, 0xaa, 0x4b, 0x13,
	0x66, 0x84, 0x3d, 0x41, 0x76, 0xb6, 0x93, 0x2f, 0x93, 0x71, 0x2f, 0xeb, 0xfb, 0x6b, 0x74, 0xbb,
	0x10, 0x0d, 0x95, 0x3c, 0x43, 0xeb, 0x29, 0x33, 0xb4, 0xab, 0x61, 0x54, 0xa3, 0xbc, 0x50, 0x51,
	0x3a, 0x80, 0xf4, 0x41, 0xcc, 0xbc, 0x49, 0x19, 0x31, 0xab, 0x9a, 0xc5, 0x77, 0x0b, 0xaa, 0xc8,
	0xd3, 0x2c, 0xab, 0x62, 0xed, 0x4a, 0x55, 0xac, 0x6c, 0x36, 0xed, 0x9f, 0x15, 0x74, 0x4d, 0x09,
	0xc5, 0x3d, 0x54, 0xd5, 0x1b, 0x83, 0xef, 0xa4, 0x74, 0x98, 0xab, 0x68, 0x3b, 0xcb, 0xdc, 0x3a,
	0x3d, 0xd9, 0x3a, 0xfd, 0xf1, 0xf7, 0x6b, 0x79, 0x13, 0xd7, 0x68, 0xfe, 0x30, 0xe0, 0xe1, 0xfc,
	0x19, 0xe2, 0x7b, 0xf9, 0x2c, 0xc6, 0x46, 0xda, 0xe4, 0x22, 0x08, 0x90, 0x6d, 0x2b, 0xb2, 0x2d,
	0xdc, 0xa4, 0xc6, 0xb5, 0xa1, 0x1f, 0xfd, 0xfe, 0x27, 0x2c, 0x10, 0x82, 0x98, 0x4e, 0x10, 0x98,
	0xac, 0xc6, 0x3a, 0x9a, 0xac, 0xe6, 0x3a, 0x11, 0x5b, 0xb1, 0xd6, 0x31, 0x36, 0x59, 0xf1, 0xa9,
	0x95, 0x99, 0x2d, 0x7e, 0xb0, 0xb4, 0x8a, 0xf4, 0xcb, 0xb3, 0x77, 0x2e, 0x83, 0x01, 0xf5, 0x7d,
	0x45, 0xed, 0xe0, 0x16, 0x2d, 0xbe, 0xa2, 0xba, 0xea, 0xcf, 0x16, 0xda, 0x48, 0x45, 0x77, 0x8a,
	0x74, 0x14, 0x6e, 0x80, 0xa9, 0xa3, 0xf8, 0x05, 0x5f, 0xd0, 0x78, 0xad, 0x63, 0xff, 0xf1, 0xd9,
	0xc4, 0xb1, 0xce, 0x27, 0x8e, 0xf5, 0x67, 0xe2, 0x58, 0x5f, 0xa6, 0x4e, 0xe9, 0x7c, 0xea, 0x94,
	0x7e, 0x4d, 0x9d, 0xd2, 0xab, 0x9a, 0x02, 0x7f, 0xd0, 0x31, 0xf1, 0x38, 0xe2, 0xb2, 0x57, 0x55,
	0xb7, 0xff, 0xe9, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x0c, 0xa8, 0xa3, 0xce, 0x06, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of Animals items.
	Animals(ctx context.Context, in *QueryGetAnimalsRequest, opts ...grpc.CallOption) (*QueryGetAnimalsResponse, error)
	AnimalsAll(ctx context.Context, in *QueryAllAnimalsRequest, opts ...grpc.CallOption) (*QueryAllAnimalsResponse, error)
	// Queries a list of AnimalSkill items.
	AnimalSkill(ctx context.Context, in *QueryGetAnimalSkillRequest, opts ...grpc.CallOption) (*QueryGetAnimalSkillResponse, error)
	AnimalSkillAll(ctx context.Context, in *QueryAllAnimalSkillRequest, opts ...grpc.CallOption) (*QueryAllAnimalSkillResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/capy.capy.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Animals(ctx context.Context, in *QueryGetAnimalsRequest, opts ...grpc.CallOption) (*QueryGetAnimalsResponse, error) {
	out := new(QueryGetAnimalsResponse)
	err := c.cc.Invoke(ctx, "/capy.capy.Query/Animals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AnimalsAll(ctx context.Context, in *QueryAllAnimalsRequest, opts ...grpc.CallOption) (*QueryAllAnimalsResponse, error) {
	out := new(QueryAllAnimalsResponse)
	err := c.cc.Invoke(ctx, "/capy.capy.Query/AnimalsAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AnimalSkill(ctx context.Context, in *QueryGetAnimalSkillRequest, opts ...grpc.CallOption) (*QueryGetAnimalSkillResponse, error) {
	out := new(QueryGetAnimalSkillResponse)
	err := c.cc.Invoke(ctx, "/capy.capy.Query/AnimalSkill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AnimalSkillAll(ctx context.Context, in *QueryAllAnimalSkillRequest, opts ...grpc.CallOption) (*QueryAllAnimalSkillResponse, error) {
	out := new(QueryAllAnimalSkillResponse)
	err := c.cc.Invoke(ctx, "/capy.capy.Query/AnimalSkillAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of Animals items.
	Animals(context.Context, *QueryGetAnimalsRequest) (*QueryGetAnimalsResponse, error)
	AnimalsAll(context.Context, *QueryAllAnimalsRequest) (*QueryAllAnimalsResponse, error)
	// Queries a list of AnimalSkill items.
	AnimalSkill(context.Context, *QueryGetAnimalSkillRequest) (*QueryGetAnimalSkillResponse, error)
	AnimalSkillAll(context.Context, *QueryAllAnimalSkillRequest) (*QueryAllAnimalSkillResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Animals(ctx context.Context, req *QueryGetAnimalsRequest) (*QueryGetAnimalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Animals not implemented")
}
func (*UnimplementedQueryServer) AnimalsAll(ctx context.Context, req *QueryAllAnimalsRequest) (*QueryAllAnimalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnimalsAll not implemented")
}
func (*UnimplementedQueryServer) AnimalSkill(ctx context.Context, req *QueryGetAnimalSkillRequest) (*QueryGetAnimalSkillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnimalSkill not implemented")
}
func (*UnimplementedQueryServer) AnimalSkillAll(ctx context.Context, req *QueryAllAnimalSkillRequest) (*QueryAllAnimalSkillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnimalSkillAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/capy.capy.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Animals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAnimalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Animals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/capy.capy.Query/Animals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Animals(ctx, req.(*QueryGetAnimalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AnimalsAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllAnimalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AnimalsAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/capy.capy.Query/AnimalsAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AnimalsAll(ctx, req.(*QueryAllAnimalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AnimalSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAnimalSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AnimalSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/capy.capy.Query/AnimalSkill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AnimalSkill(ctx, req.(*QueryGetAnimalSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AnimalSkillAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllAnimalSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AnimalSkillAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/capy.capy.Query/AnimalSkillAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AnimalSkillAll(ctx, req.(*QueryAllAnimalSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "capy.capy.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Animals",
			Handler:    _Query_Animals_Handler,
		},
		{
			MethodName: "AnimalsAll",
			Handler:    _Query_AnimalsAll_Handler,
		},
		{
			MethodName: "AnimalSkill",
			Handler:    _Query_AnimalSkill_Handler,
		},
		{
			MethodName: "AnimalSkillAll",
			Handler:    _Query_AnimalSkillAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "capy/capy/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetAnimalsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAnimalsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAnimalsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAnimalsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAnimalsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAnimalsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Animals.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllAnimalsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllAnimalsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllAnimalsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllAnimalsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllAnimalsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllAnimalsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Animals) > 0 {
		for iNdEx := len(m.Animals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Animals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAnimalSkillRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAnimalSkillRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAnimalSkillRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAnimalSkillResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAnimalSkillResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAnimalSkillResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.AnimalSkill.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllAnimalSkillRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllAnimalSkillRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllAnimalSkillRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllAnimalSkillResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllAnimalSkillResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllAnimalSkillResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.AnimalSkill) > 0 {
		for iNdEx := len(m.AnimalSkill) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AnimalSkill[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetAnimalsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetAnimalsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Animals.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllAnimalsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllAnimalsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Animals) > 0 {
		for _, e := range m.Animals {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAnimalSkillRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetAnimalSkillResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.AnimalSkill.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllAnimalSkillRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllAnimalSkillResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AnimalSkill) > 0 {
		for _, e := range m.AnimalSkill {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAnimalsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAnimalsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAnimalsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAnimalsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAnimalsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAnimalsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Animals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Animals.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllAnimalsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllAnimalsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllAnimalsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllAnimalsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllAnimalsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllAnimalsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Animals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Animals = append(m.Animals, Animals{})
			if err := m.Animals[len(m.Animals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAnimalSkillRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAnimalSkillRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAnimalSkillRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAnimalSkillResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAnimalSkillResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAnimalSkillResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AnimalSkill", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AnimalSkill.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllAnimalSkillRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllAnimalSkillRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllAnimalSkillRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllAnimalSkillResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllAnimalSkillResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllAnimalSkillResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AnimalSkill", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AnimalSkill = append(m.AnimalSkill, AnimalSkill{})
			if err := m.AnimalSkill[len(m.AnimalSkill)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
