// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: capy/capy/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateAnimals struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Power    uint64 `protobuf:"varint,3,opt,name=power,proto3" json:"power,omitempty"`
	Hp       uint64 `protobuf:"varint,4,opt,name=hp,proto3" json:"hp,omitempty"`
	Location string `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
}

func (m *MsgCreateAnimals) Reset()         { *m = MsgCreateAnimals{} }
func (m *MsgCreateAnimals) String() string { return proto.CompactTextString(m) }
func (*MsgCreateAnimals) ProtoMessage()    {}
func (*MsgCreateAnimals) Descriptor() ([]byte, []int) {
	return fileDescriptor_0365bbcac918fd7c, []int{0}
}
func (m *MsgCreateAnimals) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateAnimals) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateAnimals.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateAnimals) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateAnimals.Merge(m, src)
}
func (m *MsgCreateAnimals) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateAnimals) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateAnimals.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateAnimals proto.InternalMessageInfo

func (m *MsgCreateAnimals) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateAnimals) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgCreateAnimals) GetPower() uint64 {
	if m != nil {
		return m.Power
	}
	return 0
}

func (m *MsgCreateAnimals) GetHp() uint64 {
	if m != nil {
		return m.Hp
	}
	return 0
}

func (m *MsgCreateAnimals) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

type MsgCreateAnimalsResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCreateAnimalsResponse) Reset()         { *m = MsgCreateAnimalsResponse{} }
func (m *MsgCreateAnimalsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateAnimalsResponse) ProtoMessage()    {}
func (*MsgCreateAnimalsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0365bbcac918fd7c, []int{1}
}
func (m *MsgCreateAnimalsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateAnimalsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateAnimalsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateAnimalsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateAnimalsResponse.Merge(m, src)
}
func (m *MsgCreateAnimalsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateAnimalsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateAnimalsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateAnimalsResponse proto.InternalMessageInfo

func (m *MsgCreateAnimalsResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgUpdateAnimals struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id       uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Power    uint64 `protobuf:"varint,4,opt,name=power,proto3" json:"power,omitempty"`
	Hp       uint64 `protobuf:"varint,5,opt,name=hp,proto3" json:"hp,omitempty"`
	Location string `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
}

func (m *MsgUpdateAnimals) Reset()         { *m = MsgUpdateAnimals{} }
func (m *MsgUpdateAnimals) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateAnimals) ProtoMessage()    {}
func (*MsgUpdateAnimals) Descriptor() ([]byte, []int) {
	return fileDescriptor_0365bbcac918fd7c, []int{2}
}
func (m *MsgUpdateAnimals) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateAnimals) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateAnimals.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateAnimals) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateAnimals.Merge(m, src)
}
func (m *MsgUpdateAnimals) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateAnimals) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateAnimals.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateAnimals proto.InternalMessageInfo

func (m *MsgUpdateAnimals) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateAnimals) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgUpdateAnimals) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgUpdateAnimals) GetPower() uint64 {
	if m != nil {
		return m.Power
	}
	return 0
}

func (m *MsgUpdateAnimals) GetHp() uint64 {
	if m != nil {
		return m.Hp
	}
	return 0
}

func (m *MsgUpdateAnimals) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

type MsgUpdateAnimalsResponse struct {
}

func (m *MsgUpdateAnimalsResponse) Reset()         { *m = MsgUpdateAnimalsResponse{} }
func (m *MsgUpdateAnimalsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateAnimalsResponse) ProtoMessage()    {}
func (*MsgUpdateAnimalsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0365bbcac918fd7c, []int{3}
}
func (m *MsgUpdateAnimalsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateAnimalsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateAnimalsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateAnimalsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateAnimalsResponse.Merge(m, src)
}
func (m *MsgUpdateAnimalsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateAnimalsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateAnimalsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateAnimalsResponse proto.InternalMessageInfo

type MsgDeleteAnimals struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgDeleteAnimals) Reset()         { *m = MsgDeleteAnimals{} }
func (m *MsgDeleteAnimals) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteAnimals) ProtoMessage()    {}
func (*MsgDeleteAnimals) Descriptor() ([]byte, []int) {
	return fileDescriptor_0365bbcac918fd7c, []int{4}
}
func (m *MsgDeleteAnimals) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteAnimals) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteAnimals.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteAnimals) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteAnimals.Merge(m, src)
}
func (m *MsgDeleteAnimals) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteAnimals) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteAnimals.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteAnimals proto.InternalMessageInfo

func (m *MsgDeleteAnimals) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDeleteAnimals) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgDeleteAnimalsResponse struct {
}

func (m *MsgDeleteAnimalsResponse) Reset()         { *m = MsgDeleteAnimalsResponse{} }
func (m *MsgDeleteAnimalsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteAnimalsResponse) ProtoMessage()    {}
func (*MsgDeleteAnimalsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0365bbcac918fd7c, []int{5}
}
func (m *MsgDeleteAnimalsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteAnimalsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteAnimalsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteAnimalsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteAnimalsResponse.Merge(m, src)
}
func (m *MsgDeleteAnimalsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteAnimalsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteAnimalsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteAnimalsResponse proto.InternalMessageInfo

type MsgCreateAnimalSkill struct {
	Creator string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Skill   []uint64 `protobuf:"varint,2,rep,packed,name=skill,proto3" json:"skill,omitempty"`
}

func (m *MsgCreateAnimalSkill) Reset()         { *m = MsgCreateAnimalSkill{} }
func (m *MsgCreateAnimalSkill) String() string { return proto.CompactTextString(m) }
func (*MsgCreateAnimalSkill) ProtoMessage()    {}
func (*MsgCreateAnimalSkill) Descriptor() ([]byte, []int) {
	return fileDescriptor_0365bbcac918fd7c, []int{6}
}
func (m *MsgCreateAnimalSkill) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateAnimalSkill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateAnimalSkill.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateAnimalSkill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateAnimalSkill.Merge(m, src)
}
func (m *MsgCreateAnimalSkill) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateAnimalSkill) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateAnimalSkill.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateAnimalSkill proto.InternalMessageInfo

func (m *MsgCreateAnimalSkill) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateAnimalSkill) GetSkill() []uint64 {
	if m != nil {
		return m.Skill
	}
	return nil
}

type MsgCreateAnimalSkillResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCreateAnimalSkillResponse) Reset()         { *m = MsgCreateAnimalSkillResponse{} }
func (m *MsgCreateAnimalSkillResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateAnimalSkillResponse) ProtoMessage()    {}
func (*MsgCreateAnimalSkillResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0365bbcac918fd7c, []int{7}
}
func (m *MsgCreateAnimalSkillResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateAnimalSkillResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateAnimalSkillResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateAnimalSkillResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateAnimalSkillResponse.Merge(m, src)
}
func (m *MsgCreateAnimalSkillResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateAnimalSkillResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateAnimalSkillResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateAnimalSkillResponse proto.InternalMessageInfo

func (m *MsgCreateAnimalSkillResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgUpdateAnimalSkill struct {
	Creator string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Skill   []uint64 `protobuf:"varint,3,rep,packed,name=skill,proto3" json:"skill,omitempty"`
}

func (m *MsgUpdateAnimalSkill) Reset()         { *m = MsgUpdateAnimalSkill{} }
func (m *MsgUpdateAnimalSkill) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateAnimalSkill) ProtoMessage()    {}
func (*MsgUpdateAnimalSkill) Descriptor() ([]byte, []int) {
	return fileDescriptor_0365bbcac918fd7c, []int{8}
}
func (m *MsgUpdateAnimalSkill) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateAnimalSkill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateAnimalSkill.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateAnimalSkill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateAnimalSkill.Merge(m, src)
}
func (m *MsgUpdateAnimalSkill) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateAnimalSkill) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateAnimalSkill.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateAnimalSkill proto.InternalMessageInfo

func (m *MsgUpdateAnimalSkill) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateAnimalSkill) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgUpdateAnimalSkill) GetSkill() []uint64 {
	if m != nil {
		return m.Skill
	}
	return nil
}

type MsgUpdateAnimalSkillResponse struct {
}

func (m *MsgUpdateAnimalSkillResponse) Reset()         { *m = MsgUpdateAnimalSkillResponse{} }
func (m *MsgUpdateAnimalSkillResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateAnimalSkillResponse) ProtoMessage()    {}
func (*MsgUpdateAnimalSkillResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0365bbcac918fd7c, []int{9}
}
func (m *MsgUpdateAnimalSkillResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateAnimalSkillResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateAnimalSkillResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateAnimalSkillResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateAnimalSkillResponse.Merge(m, src)
}
func (m *MsgUpdateAnimalSkillResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateAnimalSkillResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateAnimalSkillResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateAnimalSkillResponse proto.InternalMessageInfo

type MsgDeleteAnimalSkill struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgDeleteAnimalSkill) Reset()         { *m = MsgDeleteAnimalSkill{} }
func (m *MsgDeleteAnimalSkill) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteAnimalSkill) ProtoMessage()    {}
func (*MsgDeleteAnimalSkill) Descriptor() ([]byte, []int) {
	return fileDescriptor_0365bbcac918fd7c, []int{10}
}
func (m *MsgDeleteAnimalSkill) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteAnimalSkill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteAnimalSkill.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteAnimalSkill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteAnimalSkill.Merge(m, src)
}
func (m *MsgDeleteAnimalSkill) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteAnimalSkill) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteAnimalSkill.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteAnimalSkill proto.InternalMessageInfo

func (m *MsgDeleteAnimalSkill) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDeleteAnimalSkill) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgDeleteAnimalSkillResponse struct {
}

func (m *MsgDeleteAnimalSkillResponse) Reset()         { *m = MsgDeleteAnimalSkillResponse{} }
func (m *MsgDeleteAnimalSkillResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteAnimalSkillResponse) ProtoMessage()    {}
func (*MsgDeleteAnimalSkillResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0365bbcac918fd7c, []int{11}
}
func (m *MsgDeleteAnimalSkillResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteAnimalSkillResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteAnimalSkillResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteAnimalSkillResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteAnimalSkillResponse.Merge(m, src)
}
func (m *MsgDeleteAnimalSkillResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteAnimalSkillResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteAnimalSkillResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteAnimalSkillResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateAnimals)(nil), "capy.capy.MsgCreateAnimals")
	proto.RegisterType((*MsgCreateAnimalsResponse)(nil), "capy.capy.MsgCreateAnimalsResponse")
	proto.RegisterType((*MsgUpdateAnimals)(nil), "capy.capy.MsgUpdateAnimals")
	proto.RegisterType((*MsgUpdateAnimalsResponse)(nil), "capy.capy.MsgUpdateAnimalsResponse")
	proto.RegisterType((*MsgDeleteAnimals)(nil), "capy.capy.MsgDeleteAnimals")
	proto.RegisterType((*MsgDeleteAnimalsResponse)(nil), "capy.capy.MsgDeleteAnimalsResponse")
	proto.RegisterType((*MsgCreateAnimalSkill)(nil), "capy.capy.MsgCreateAnimalSkill")
	proto.RegisterType((*MsgCreateAnimalSkillResponse)(nil), "capy.capy.MsgCreateAnimalSkillResponse")
	proto.RegisterType((*MsgUpdateAnimalSkill)(nil), "capy.capy.MsgUpdateAnimalSkill")
	proto.RegisterType((*MsgUpdateAnimalSkillResponse)(nil), "capy.capy.MsgUpdateAnimalSkillResponse")
	proto.RegisterType((*MsgDeleteAnimalSkill)(nil), "capy.capy.MsgDeleteAnimalSkill")
	proto.RegisterType((*MsgDeleteAnimalSkillResponse)(nil), "capy.capy.MsgDeleteAnimalSkillResponse")
}

func init() { proto.RegisterFile("capy/capy/tx.proto", fileDescriptor_0365bbcac918fd7c) }

var fileDescriptor_0365bbcac918fd7c = []byte{
	// 465 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0xb5, 0xbe, 0xdc, 0x7a, 0xc1, 0xa5, 0x5e, 0x0c, 0x5d, 0x54, 0x23, 0x1b, 0xf5, 0x50, 0xd3,
	0x82, 0x0a, 0xed, 0xb5, 0x87, 0x7e, 0xd1, 0x9b, 0x0f, 0x56, 0x69, 0x0e, 0x81, 0x10, 0x14, 0x7b,
	0xb1, 0x45, 0x64, 0x69, 0x91, 0x04, 0xb1, 0xaf, 0xf9, 0x05, 0x21, 0xd7, 0xfc, 0xa1, 0x1c, 0x7d,
	0xcc, 0x31, 0xd8, 0x7f, 0x24, 0xec, 0xc8, 0x52, 0xa4, 0x95, 0x64, 0x27, 0xb9, 0x08, 0xcd, 0xce,
	0xce, 0x9b, 0xf7, 0x76, 0xde, 0x2e, 0xc2, 0x13, 0x87, 0xad, 0xbe, 0xc0, 0x27, 0x5e, 0x5a, 0x2c,
	0x0c, 0xe2, 0x00, 0xb7, 0x78, 0x68, 0xf1, 0x8f, 0xfe, 0xee, 0x31, 0xed, 0xf8, 0xee, 0xc2, 0xf1,
	0xa2, 0x64, 0x8f, 0xde, 0x13, 0x13, 0xa7, 0xd1, 0xb9, 0xeb, 0x79, 0x49, 0xd6, 0xbc, 0x94, 0xd0,
	0xdb, 0x51, 0x34, 0xfb, 0x1d, 0x52, 0x27, 0xa6, 0x3f, 0x93, 0x42, 0x4c, 0xd0, 0xab, 0x09, 0x5f,
	0x08, 0x42, 0x22, 0x0d, 0xa4, 0x61, 0xcb, 0x4e, 0x43, 0x8c, 0x91, 0xea, 0x3b, 0x0b, 0x4a, 0x64,
	0x58, 0x86, 0x7f, 0xdc, 0x45, 0x1a, 0x0b, 0x2e, 0x68, 0x48, 0x94, 0x81, 0x34, 0x54, 0xed, 0x24,
	0xc0, 0x6f, 0x90, 0x3c, 0x67, 0x44, 0x85, 0x25, 0x79, 0xce, 0xb0, 0x8e, 0x5e, 0x7b, 0xc1, 0xc4,
	0x89, 0xdd, 0xc0, 0x27, 0x1a, 0x54, 0x67, 0xb1, 0xf9, 0x09, 0x11, 0x91, 0x83, 0x4d, 0x23, 0x16,
	0xf8, 0x11, 0xe5, 0x38, 0xee, 0x14, 0x68, 0xa8, 0xb6, 0xec, 0x4e, 0xcd, 0xeb, 0x84, 0xf0, 0x7f,
	0x36, 0x7d, 0x12, 0xe1, 0xa4, 0x5c, 0x4e, 0xcb, 0x33, 0x01, 0x4a, 0x95, 0x00, 0xb5, 0x2c, 0x40,
	0xab, 0x14, 0xd0, 0x14, 0x04, 0xe8, 0x20, 0xa0, 0xc0, 0x29, 0x15, 0x60, 0x7e, 0x07, 0xbe, 0x7f,
	0xa8, 0x47, 0x5f, 0xc0, 0x77, 0x87, 0x5c, 0xa8, 0xce, 0x90, 0xff, 0xa2, 0xae, 0x70, 0x6c, 0xff,
	0xf8, 0x64, 0xf7, 0xa0, 0x77, 0x91, 0x06, 0xc3, 0x27, 0xf2, 0x40, 0xe1, 0x4a, 0x21, 0x30, 0x2d,
	0xd4, 0xab, 0xc2, 0xa9, 0x1d, 0xc1, 0x11, 0xf4, 0xcd, 0xab, 0x3d, 0xd4, 0x57, 0x9c, 0x42, 0xc6,
	0x43, 0xc9, 0xf3, 0x30, 0x80, 0x47, 0x09, 0x37, 0xd3, 0xfb, 0x03, 0xfa, 0xe6, 0xcf, 0xe2, 0x99,
	0x7d, 0x77, 0x1d, 0x4a, 0x08, 0x69, 0x87, 0xaf, 0x37, 0x2a, 0x52, 0x46, 0xd1, 0x0c, 0x8f, 0x51,
	0xbb, 0x78, 0x23, 0xde, 0x5b, 0xd9, 0x4d, 0xb3, 0x44, 0xab, 0xea, 0x1f, 0xf6, 0x24, 0xb3, 0x43,
	0x1c, 0xa3, 0x76, 0xd1, 0xb3, 0x02, 0x64, 0x21, 0x29, 0x42, 0x56, 0x3a, 0x8b, 0x43, 0x16, 0x6d,
	0x25, 0x40, 0x16, 0x92, 0x22, 0x64, 0xa5, 0xa5, 0xf0, 0x09, 0xea, 0x94, 0xfd, 0xd4, 0xaf, 0xd7,
	0x07, 0x1b, 0xf4, 0x8f, 0x07, 0x36, 0xe4, 0xe1, 0xcb, 0xb6, 0xe9, 0xd7, 0x6b, 0xad, 0x84, 0xaf,
	0x35, 0x08, 0x87, 0x2f, 0xbb, 0xa3, 0x5f, 0xaf, 0xbb, 0x12, 0xbe, 0xd6, 0x1d, 0xbf, 0x3e, 0xdf,
	0x6e, 0x0c, 0x69, 0xbd, 0x31, 0xa4, 0xfb, 0x8d, 0x21, 0x5d, 0x6d, 0x8d, 0xc6, 0x7a, 0x6b, 0x34,
	0xee, 0xb6, 0x46, 0xe3, 0xb8, 0x03, 0xcf, 0xeb, 0x72, 0xf7, 0x3a, 0xaf, 0x18, 0x8d, 0xce, 0x9a,
	0xf0, 0xbe, 0x7e, 0x7b, 0x08, 0x00, 0x00, 0xff, 0xff, 0xa4, 0x75, 0x3a, 0xfe, 0xb7, 0x05, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateAnimals(ctx context.Context, in *MsgCreateAnimals, opts ...grpc.CallOption) (*MsgCreateAnimalsResponse, error)
	UpdateAnimals(ctx context.Context, in *MsgUpdateAnimals, opts ...grpc.CallOption) (*MsgUpdateAnimalsResponse, error)
	DeleteAnimals(ctx context.Context, in *MsgDeleteAnimals, opts ...grpc.CallOption) (*MsgDeleteAnimalsResponse, error)
	CreateAnimalSkill(ctx context.Context, in *MsgCreateAnimalSkill, opts ...grpc.CallOption) (*MsgCreateAnimalSkillResponse, error)
	UpdateAnimalSkill(ctx context.Context, in *MsgUpdateAnimalSkill, opts ...grpc.CallOption) (*MsgUpdateAnimalSkillResponse, error)
	DeleteAnimalSkill(ctx context.Context, in *MsgDeleteAnimalSkill, opts ...grpc.CallOption) (*MsgDeleteAnimalSkillResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateAnimals(ctx context.Context, in *MsgCreateAnimals, opts ...grpc.CallOption) (*MsgCreateAnimalsResponse, error) {
	out := new(MsgCreateAnimalsResponse)
	err := c.cc.Invoke(ctx, "/capy.capy.Msg/CreateAnimals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateAnimals(ctx context.Context, in *MsgUpdateAnimals, opts ...grpc.CallOption) (*MsgUpdateAnimalsResponse, error) {
	out := new(MsgUpdateAnimalsResponse)
	err := c.cc.Invoke(ctx, "/capy.capy.Msg/UpdateAnimals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteAnimals(ctx context.Context, in *MsgDeleteAnimals, opts ...grpc.CallOption) (*MsgDeleteAnimalsResponse, error) {
	out := new(MsgDeleteAnimalsResponse)
	err := c.cc.Invoke(ctx, "/capy.capy.Msg/DeleteAnimals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateAnimalSkill(ctx context.Context, in *MsgCreateAnimalSkill, opts ...grpc.CallOption) (*MsgCreateAnimalSkillResponse, error) {
	out := new(MsgCreateAnimalSkillResponse)
	err := c.cc.Invoke(ctx, "/capy.capy.Msg/CreateAnimalSkill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateAnimalSkill(ctx context.Context, in *MsgUpdateAnimalSkill, opts ...grpc.CallOption) (*MsgUpdateAnimalSkillResponse, error) {
	out := new(MsgUpdateAnimalSkillResponse)
	err := c.cc.Invoke(ctx, "/capy.capy.Msg/UpdateAnimalSkill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteAnimalSkill(ctx context.Context, in *MsgDeleteAnimalSkill, opts ...grpc.CallOption) (*MsgDeleteAnimalSkillResponse, error) {
	out := new(MsgDeleteAnimalSkillResponse)
	err := c.cc.Invoke(ctx, "/capy.capy.Msg/DeleteAnimalSkill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateAnimals(context.Context, *MsgCreateAnimals) (*MsgCreateAnimalsResponse, error)
	UpdateAnimals(context.Context, *MsgUpdateAnimals) (*MsgUpdateAnimalsResponse, error)
	DeleteAnimals(context.Context, *MsgDeleteAnimals) (*MsgDeleteAnimalsResponse, error)
	CreateAnimalSkill(context.Context, *MsgCreateAnimalSkill) (*MsgCreateAnimalSkillResponse, error)
	UpdateAnimalSkill(context.Context, *MsgUpdateAnimalSkill) (*MsgUpdateAnimalSkillResponse, error)
	DeleteAnimalSkill(context.Context, *MsgDeleteAnimalSkill) (*MsgDeleteAnimalSkillResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateAnimals(ctx context.Context, req *MsgCreateAnimals) (*MsgCreateAnimalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAnimals not implemented")
}
func (*UnimplementedMsgServer) UpdateAnimals(ctx context.Context, req *MsgUpdateAnimals) (*MsgUpdateAnimalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAnimals not implemented")
}
func (*UnimplementedMsgServer) DeleteAnimals(ctx context.Context, req *MsgDeleteAnimals) (*MsgDeleteAnimalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAnimals not implemented")
}
func (*UnimplementedMsgServer) CreateAnimalSkill(ctx context.Context, req *MsgCreateAnimalSkill) (*MsgCreateAnimalSkillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAnimalSkill not implemented")
}
func (*UnimplementedMsgServer) UpdateAnimalSkill(ctx context.Context, req *MsgUpdateAnimalSkill) (*MsgUpdateAnimalSkillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAnimalSkill not implemented")
}
func (*UnimplementedMsgServer) DeleteAnimalSkill(ctx context.Context, req *MsgDeleteAnimalSkill) (*MsgDeleteAnimalSkillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAnimalSkill not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateAnimals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateAnimals)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateAnimals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/capy.capy.Msg/CreateAnimals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateAnimals(ctx, req.(*MsgCreateAnimals))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateAnimals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateAnimals)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateAnimals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/capy.capy.Msg/UpdateAnimals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateAnimals(ctx, req.(*MsgUpdateAnimals))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteAnimals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteAnimals)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteAnimals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/capy.capy.Msg/DeleteAnimals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteAnimals(ctx, req.(*MsgDeleteAnimals))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateAnimalSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateAnimalSkill)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateAnimalSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/capy.capy.Msg/CreateAnimalSkill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateAnimalSkill(ctx, req.(*MsgCreateAnimalSkill))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateAnimalSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateAnimalSkill)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateAnimalSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/capy.capy.Msg/UpdateAnimalSkill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateAnimalSkill(ctx, req.(*MsgUpdateAnimalSkill))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteAnimalSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteAnimalSkill)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteAnimalSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/capy.capy.Msg/DeleteAnimalSkill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteAnimalSkill(ctx, req.(*MsgDeleteAnimalSkill))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "capy.capy.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAnimals",
			Handler:    _Msg_CreateAnimals_Handler,
		},
		{
			MethodName: "UpdateAnimals",
			Handler:    _Msg_UpdateAnimals_Handler,
		},
		{
			MethodName: "DeleteAnimals",
			Handler:    _Msg_DeleteAnimals_Handler,
		},
		{
			MethodName: "CreateAnimalSkill",
			Handler:    _Msg_CreateAnimalSkill_Handler,
		},
		{
			MethodName: "UpdateAnimalSkill",
			Handler:    _Msg_UpdateAnimalSkill_Handler,
		},
		{
			MethodName: "DeleteAnimalSkill",
			Handler:    _Msg_DeleteAnimalSkill_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "capy/capy/tx.proto",
}

func (m *MsgCreateAnimals) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateAnimals) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateAnimals) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Location) > 0 {
		i -= len(m.Location)
		copy(dAtA[i:], m.Location)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Location)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Hp != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Hp))
		i--
		dAtA[i] = 0x20
	}
	if m.Power != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Power))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateAnimalsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateAnimalsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateAnimalsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateAnimals) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateAnimals) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateAnimals) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Location) > 0 {
		i -= len(m.Location)
		copy(dAtA[i:], m.Location)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Location)))
		i--
		dAtA[i] = 0x32
	}
	if m.Hp != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Hp))
		i--
		dAtA[i] = 0x28
	}
	if m.Power != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Power))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateAnimalsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateAnimalsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateAnimalsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteAnimals) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteAnimals) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteAnimals) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteAnimalsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteAnimalsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteAnimalsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreateAnimalSkill) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateAnimalSkill) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateAnimalSkill) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Skill) > 0 {
		dAtA2 := make([]byte, len(m.Skill)*10)
		var j1 int
		for _, num := range m.Skill {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintTx(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateAnimalSkillResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateAnimalSkillResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateAnimalSkillResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateAnimalSkill) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateAnimalSkill) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateAnimalSkill) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Skill) > 0 {
		dAtA4 := make([]byte, len(m.Skill)*10)
		var j3 int
		for _, num := range m.Skill {
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		i -= j3
		copy(dAtA[i:], dAtA4[:j3])
		i = encodeVarintTx(dAtA, i, uint64(j3))
		i--
		dAtA[i] = 0x1a
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateAnimalSkillResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateAnimalSkillResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateAnimalSkillResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteAnimalSkill) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteAnimalSkill) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteAnimalSkill) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteAnimalSkillResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteAnimalSkillResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteAnimalSkillResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateAnimals) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Power != 0 {
		n += 1 + sovTx(uint64(m.Power))
	}
	if m.Hp != 0 {
		n += 1 + sovTx(uint64(m.Hp))
	}
	l = len(m.Location)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateAnimalsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgUpdateAnimals) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Power != 0 {
		n += 1 + sovTx(uint64(m.Power))
	}
	if m.Hp != 0 {
		n += 1 + sovTx(uint64(m.Hp))
	}
	l = len(m.Location)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateAnimalsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteAnimals) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgDeleteAnimalsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreateAnimalSkill) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Skill) > 0 {
		l = 0
		for _, e := range m.Skill {
			l += sovTx(uint64(e))
		}
		n += 1 + sovTx(uint64(l)) + l
	}
	return n
}

func (m *MsgCreateAnimalSkillResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgUpdateAnimalSkill) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	if len(m.Skill) > 0 {
		l = 0
		for _, e := range m.Skill {
			l += sovTx(uint64(e))
		}
		n += 1 + sovTx(uint64(l)) + l
	}
	return n
}

func (m *MsgUpdateAnimalSkillResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteAnimalSkill) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgDeleteAnimalSkillResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateAnimals) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateAnimals: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateAnimals: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Power", wireType)
			}
			m.Power = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Power |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hp", wireType)
			}
			m.Hp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Hp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Location", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Location = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateAnimalsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateAnimalsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateAnimalsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateAnimals) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateAnimals: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateAnimals: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Power", wireType)
			}
			m.Power = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Power |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hp", wireType)
			}
			m.Hp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Hp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Location", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Location = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateAnimalsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateAnimalsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateAnimalsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteAnimals) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteAnimals: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteAnimals: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteAnimalsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteAnimalsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteAnimalsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateAnimalSkill) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateAnimalSkill: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateAnimalSkill: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Skill = append(m.Skill, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTx
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTx
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Skill) == 0 {
					m.Skill = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTx
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Skill = append(m.Skill, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Skill", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateAnimalSkillResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateAnimalSkillResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateAnimalSkillResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateAnimalSkill) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateAnimalSkill: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateAnimalSkill: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Skill = append(m.Skill, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTx
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTx
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Skill) == 0 {
					m.Skill = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTx
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Skill = append(m.Skill, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Skill", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateAnimalSkillResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateAnimalSkillResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateAnimalSkillResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteAnimalSkill) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteAnimalSkill: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteAnimalSkill: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteAnimalSkillResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteAnimalSkillResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteAnimalSkillResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
